import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { BouncyDiv } from '../styles/styled'
import InputEmoji from "react-input-emoji";
import { useEffect, useState } from 'react';
import { motion } from "framer-motion"

import * as uuid from 'uuid';

import io from 'socket.io-client';

interface Message {
  id: string;
  name: string;
  text: string;
}

interface Payload {
  name: string;
  text: string;
}

const socket = io('http://localhost:3333');

const NChat: NextPage = () => {
  const [name, setName] = useState("");
  const [text, setText] = useState('');
  const [messages, setMessages] = useState<Message[]>([]);

  // useEffect(() => {
  //   const getName = localStorage.getItem('name')
  //   setName(getName || '')
  // }, [])

  useEffect(() => {
    function receivedMessage(message: Payload) {
      const newMessage: Message = {
        id: uuid.v4(),
        name: message.name,
        text: message.text,
      };

      setMessages([...messages, newMessage]);
    }

    socket.on('msgToClient', (message: Payload) => {
      receivedMessage(message);
    });
  }, [messages, name, text]);

  console.log(messages)

  function validateInput() {
    return name.length > 0 && text.length > 0;
  }

  function sendMessage() {
    if (validateInput()) {
      const message: Payload = {
        name,
        text,
      };

      socket.emit('msgToServer', message);
      setText('');
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <main className={styles.main}>
        <h1 className={styles.title}>
          Se divirta, <label className={styles.hello}>{name}!</label>
        </h1>

        <p className={styles.description}>
          O chat é público, seja educado.
        </p>

        <input
          type="text"
          value={name}
          onChange={e => setName(e.target.value)}
          placeholder="Enter name..."
        />

        <BouncyDiv>
          <div className={styles.grid}>
            <div className={styles.card}>
              <h2>chat &rarr;</h2>

              <div
                style={{
                  display: 'flex',
                  flexDirection: 'column'
                }}
              >
                <motion.div
                  className={styles.cardMessage}
                  animate={{
                    scale: [0, 0, 1, 1, 1],
                  }}
                >
                  <p>
                    someone:
                  </p>
                  oi
                </motion.div>

                <motion.div
                  className={styles.cardMessageMe}
                  animate={{
                    scale: [0, 0, 1, 1, 1],
                  }}
                >
                  <p>
                    {name}:
                  </p>
                  oi
                </motion.div>

              </div>

              <input
                value={text}
                onChange={e => setText(e.target.value)}
                placeholder="Enter message..."
              />
              <button type="button" onClick={() => sendMessage()}>
                Send
              </button>
            </div>
          </div>
        </BouncyDiv>

      </main>
      {/* <footer className={styles.footer}>
        <h3 className={styles.powered}>
          Powered by Luís
        </h3>
      </footer> */}
    </div>
  )
}


export default NChat
